In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

In [2]:
DATA_ROOT = "./data"
conn = sqlite3.connect(Path(DATA_ROOT) / "database.db")

# Question 1
## How many active, non delivered, shipments are currently in the pipeline

In [3]:
path = Path("./scripts/sql/question_1.sql")

with open(path, "r", encoding="utf-8") as f:
    query = f.read()

df_q1 = pd.read_sql_query(query, conn)
df_q1

   active
0     414

# Question 2
## What is the average lead time per mode of transport per trade lane?

In [4]:
path = Path("./scripts/sql/question_2.sql")

with open(path, "r", encoding="utf-8") as f:
    query = f.read()

df_q2 = pd.read_sql_query(query, conn)
df_q2

,mode_of_transport,origin_country,destination_country,n_shipments,avg_lead_time_days
0,Air,CA,GB,3,7.666667
1,Air,CA,NL,4,5.750000
2,Air,CN,CA,1,12.000000
3,Air,CN,GB,10,7.300000
4,Air,CN,NL,1,6.000000
5,Air,CN,US,3,5.000000
6,Air,GB,US,5,4.800000
7,Air,HK,GB,4,11.250000
8,Air,IT,US,2,7.000000
9,Air,KR,CA,1,6.000000
10,Air,PT,US,1,7.000000
11,Air,US,GB,39,6.564103
12,Air,VN,GB,9,6.000000
13,Ocean,GB,US,1,2.000000
14,Road,AT,DE,2,6.000000
15,Road,BE,GB,2,4.000000
16,Road,CA,US,2,5.000000
17,Road,CH,GB,7,4.428571
18,Road,DE,BE,1,2.000000
19,Road,DE,DE,10,1.600000
20,Road,DE,DK,2,5.000000
21,Road,DE,ES,3,7.000000
22,Road,DE,FR,3,11.666667
23,Road,DE,GB,7,2.428571
24,Road,DE,NL,2,5.000000
25,Road,DE,NO,4,8.000000
26,Road,DE,PL,6,3.575231
27,Road,DE,SE,2,5.000000
28,Road,ES,GB,7,4.642946
29,Road,ES,NL,1,2.024572
30,Road,ES,PL,2,6.000000
31,Road,ES,RO,1,0.000000
32,Road,FR,GB,4,5.250000
33,Road,GB,CH,1,9.000000
34,Road,GB,DE,1,3.103403
35,Road,GB,FI,2,11.500000
36,Road,GB,FR,1,2.000000
37,Road,GB,GB,162,0.172840
38,Road,GB,IE,8,3.000000
39,Road,GB,IT,8,2.000000
40,Road,GB,NL,7,1.285714
41,Road,GB,PL,8,2.750000
42,Road,IT,GB,4,9.000000
43,Road,IT,IT,1,0.000000
44,Road,IT,NL,3,1.666667
45,Road,MA,GB,2,12.000000
46,Road,NL,DE,4,1.000000
47,Road,NL,GB,29,6.413793
48,Road,NL,IT,1,2.000000
49,Road,NL,NL,2,0.704514
50,Road,PL,ES,1,4.000000
51,Road,PL,GB,1,6.500000
52,Road,PL,IE,3,6.333333
53,Road,PT,GB,1,6.000000
54,Road,PT,PT,1,0.000000
55,Road,TR,GB,74,1.864865
56,Road,US,CA,5,1.600000
57,Road,US,US,25,3.920000

# Question 3
## Show the shipments where estimated collection to delivery lead time is different to actual collection to delivery lead

In [5]:
path = Path("./scripts/sql/question_3.sql")

with open(path, "r", encoding="utf-8") as f:
    query = f.read()

df_q3 = pd.read_sql_query(query, conn)
df_q3

,cargo_id,mode_of_transport,estimated_lead_time_days,actual_lead_time_days
0,QIzAOb6x1a93HB/OgviTww==,Road,5,0
1,DYXFyN9HD8xj91m0TYmvnw==,Road,5,4
2,OseZv/Lrm0rlDZZ4rR4hAg==,Road,5,4
3,9AbnKVTrGXo4apQQgJXh8A==,Road,5,4
4,Xuei6laV2W58mCE/TSoIyg==,Road,7,6
5,SHTUvMwP8u6P1cXg/ATOCw==,Road,10,11
6,AN065wmYnAdbhaKyZaZdlg==,Road,11,10
7,sFJAswG4CXQr8q6zUwvfMw==,Road,3,2
8,HhwiKsZmJZpgfl8x0SgxbQ==,Road,3,2
9,5BPz4UjSp8mN9l5HGt5x5A==,Road,13,7
10,qxweLCJprxS1RPjJsIfqVg==,Road,1,0
11,x+diCfww+EsLkn6RvqikgQ==,Road,3,2
12,QFF6E58wlnQAfPHiz484dA==,Road,9,2
13,G7Q6As3lBG1QMhNRXjYUJw==,Road,6,5
14,3o7HUs5rGIf3KfB8HG7v+Q==,Road,9,10
15,86vY7ZsgpgGcZA46SMGxqQ==,Road,6,7
16,oeLf0sJmPzzkuqcXWcETbg==,Air,7,6
17,A8o/ac3ZyHJSIiCgyDuInA==,Road,4,3
18,2SUDMW5AHUxYkEidBK7u3g==,Road,7,3
19,iURlSIjq94jOxyqcYAbGNQ==,Road,4,3
20,iZApYx2KLyDylUALC+jyKw==,Road,7,6
21,zqy2YcKq7A/wT4556xxPFg==,Road,14,13
22,7VHELgv19O7t/sqH8/YBXw==,Road,3,2
23,PetDeGKuIkfbKh4DGoNYHw==,Road,3,2
24,Iexvy15lWrws7HMvjKj7Hw==,Road,3,2
25,gHShmfSj++kMsCjaeNdRgw==,Road,8,5
26,z+WPPZpYaOl+g0PJ76giCg==,Road,8,5
27,YbEzOJRLOgpKt+9d+fq3yg==,Road,8,7
28,s7Sjoh5Hssy/nbOmJ0OfMg==,Road,8,7
29,4kayqDSFT1EPrg/oRuQkkg==,Road,8,7
30,S+XiGB9NkQvlOmfW9X0jRA==,Road,8,9
31,UiIg+o/sd2b6hxyvSJtUbw==,Road,4,1
32,/P+M8bvQ1IxAh7XkrrYQDg==,Road,4,1
33,2YlVo8RE2A/QLAUSsrF6Lw==,Road,4,1
34,upKMnd/kGII8llcEq5u/fg==,Road,4,1
35,D1sRir+jodMYf4YIwXDJ8g==,Road,4,1
36,KIc3R5x5SpxgTpmVgp6zcg==,Road,4,1
37,R+arXAn86tpBUMZogMVL8w==,Road,4,1
38,A6uY/QGBrKmdoWKiwrronQ==,Road,6,2
39,otnSfFBde1rJg87/37+c0g==,Air,2,3
40,lriK1R80EbEBE9bZRtb0ew==,Road,8,9
41,dkL4tCSHgcOEqGELhTIPtw==,Road,3,2
42,odsZpvkUiAptD8n1r7iYhg==,Road,6,4
43,zAqE4GkwaB2m1qtPJwMUaw==,Road,8,2
44,VvMzBchsyQY0X2SwlLCYBg==,Road,5,4